server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: producto-service
          uri: lb://producto-service
          predicates:
            - Path=/productos/**
        - id: orden-service
          uri: lb://orden-service
          predicates:
            - Path=/ordenes/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
